unit DOpusPluginSupport;

interface

{$MINENUMSIZE 4}

uses
  Winapi.Windows;

type
  PDWORDLONG = ^DWORDLONG;
  LPCBYTE = PByte;

const
  OPUSCFG_LOAD = 0;
  OPUSCFG_SAVE = 1;

type
  DOpusPluginConfigItemType = (
    DPCITYPE_Bool,
    DPCITYPE_Int,
    DPCITYPE_DWORD,
    DPCITYPE_LPSTR,
    DPCITYPE_LPWSTR,
    DPCITYPE_Binary,
    DPCITYPE_LOGFONT,
    DPCITYPE_Child
  );

const
  DPCITYPE_LPTSTR = Ord(DPCITYPE_LPWSTR);

type
  DOPUSPLUGINCONFIGITEMA = record
    pszName: LPCSTR;
    iType: Integer;
    pData: Pointer;
    dwDataSize: DWORD;
  end;
  LPDOPUSPLUGINCONFIGITEMA = ^DOPUSPLUGINCONFIGITEMA;

  DOPUSPLUGINCONFIGDATAA = record
    cbSize: UINT;
    pszName: LPCSTR;
    fStateData: BOOL;
    iNumCfgItems: Integer;
    pCfgItemArray: LPDOPUSPLUGINCONFIGITEMA;
  end;
  LPDOPUSPLUGINCONFIGDATAA = ^DOPUSPLUGINCONFIGDATAA;

  DOPUSPLUGINCONFIGITEMW = record
    pszName: LPCWSTR;
    iType: Integer;
    pData: Pointer;
    dwDataSize: DWORD;
  end;
  LPDOPUSPLUGINCONFIGITEMW = ^DOPUSPLUGINCONFIGITEMW;

  DOPUSPLUGINCONFIGDATAW = record
    cbSize: UINT;
    pszName: LPCWSTR;
    fStateData: BOOL;
    iNumCfgItems: Integer;
    pCfgItemArray: LPDOPUSPLUGINCONFIGITEMW;
  end;
  LPDOPUSPLUGINCONFIGDATAW = ^DOPUSPLUGINCONFIGDATAW;

  DOPUSPLUGINCONFIGITEM = DOPUSPLUGINCONFIGITEMW;
  LPDOPUSPLUGINCONFIGITEM = LPDOPUSPLUGINCONFIGITEMW;
  DOPUSPLUGINCONFIGDATA = DOPUSPLUGINCONFIGDATAW;
  LPDOPUSPLUGINCONFIGDATA = LPDOPUSPLUGINCONFIGDATAW;

  DOPUSTHUMBNAILPREFSDATA = record
    cbSize: UINT;
    dwFlags: DWORD;
    crFillColor: COLORREF;
    szThumbSize: SIZE;
    szMinThumbSize: SIZE;
    szMaxThumbSize: SIZE;
  end;
  LPDOPUSTHUMBNAILPREFSDATA = ^DOPUSTHUMBNAILPREFSDATA;

const
  DTHUMBF_GRAYSCALE = DWORD(1) shl 0;
  DTHUMBF_SHOWICON = DWORD(1) shl 1;
  DTHUMBF_HIDEICON = DWORD(1) shl 2;
  DTHUMBF_USESHELL = DWORD(1) shl 3;
  DTHUMBF_HIGHQUALITY = DWORD(1) shl 4;
  DTHUMBF_FOLDERS = DWORD(1) shl 5;
  DTHUMBF_FOLDERCONTENTS = DWORD(1) shl 6;
  DTHUMBF_AUTOROTATE = DWORD(1) shl 7;

type
  DOPUSCHOOSEFONTA = record
    cbSize: UINT;
    lpFont: PLogFontA;
    dwFlags: DWORD;
    lpszTitle: LPCSTR;
  end;
  LPDOPUSCHOOSEFONTA = ^DOPUSCHOOSEFONTA;

  DOPUSCHOOSEFONTW = record
    cbSize: UINT;
    lpFont: PLogFontW;
    dwFlags: DWORD;
    lpszTitle: LPCWSTR;
  end;
  LPDOPUSCHOOSEFONTW = ^DOPUSCHOOSEFONTW;

  DOPUSCHOOSEFONT = DOPUSCHOOSEFONTW;
  LPDOPUSCHOOSEFONT = LPDOPUSCHOOSEFONTW;

const
  DCHOOSEFONTF_FIXEDONLY = DWORD(1) shl 0;

  OPUSPATH_CONFIG = 0;
  OPUSPATH_STATEDATA = 1;

  ERRORACTION_COPY = 1;
  ERRORACTION_MOVE = 2;
  ERRORACTION_DELETE = 3;

  ERRORTYPE_RETRY_SKIP_CANCEL = 1;
  ERRORTYPE_RETRY_CANCEL = 2;
  ERRORTYPE_SKIP_CANCEL = 3;
  ERRORTYPE_OK = 4;
  ERRORTYPE_OK_SKIP_CANCEL = 5;
  ERRORTYPE_SCHEDULE_RETRY_SKIP_CANCEL = 6;

  ERRORRESULT_ABORT = 0;
  ERRORRESULT_RETRY = 1;
  ERRORRESULT_SKIP = 2;
  ERRORRESULT_SKIP_ALL = 3;
  ERRORRESULT_SCHEDULE = 4;
  ERRORRESULT_SCHEDULE_ALL = 5;
  ERRORRESULT_OK = 6;

type
  PFNCHECKINPUTA = function(hWnd: HWND; lParamCheckInput: LPARAM; lpszOrigString: LPCSTR; lpszString: LPCSTR; pszErrorBuf: LPSTR; cchErrorMax: Integer): Integer; stdcall;
  PFNCHECKINPUTW = function(hWnd: HWND; lParamCheckInput: LPARAM; lpszOrigString: LPCWSTR; lpszString: LPCWSTR; pszErrorBuf: LPWSTR; cchErrorMax: Integer): Integer; stdcall;
  PFNCHECKINPUT = PFNCHECKINPUTW;

const
  CHECKINPUT_REJECT = 0;
  CHECKINPUT_ACCEPT = 1;
  CHECKINPUT_ASK = 2;

  HICON_WARNING = HICON(-1);
  HICON_ERROR = HICON(-2);
  HICON_INFO = HICON(-3);

  BUTTONS_OK_ID = NativeUInt(1);
  BUTTONS_OKCANCEL_ID = NativeUInt(2);
  BUTTONS_RETRYSKIP_ID = NativeUInt(3);
  BUTTONS_IGNORECANCEL_ID = NativeUInt(4);
  BUTTONS_RETRYSKIPABORT_ID = NativeUInt(5);
  BUTTONS_SCHEDULERETRYSKIPABORT_ID = NativeUInt(6);
  BUTTONS_REPLACESKIPABORT_ID = NativeUInt(7);
  BUTTONS_UNPROTECTSKIPABORT_ID = NativeUInt(8);
  BUTTONS_DELETESKIPABORT_ID = NativeUInt(9);
  BUTTONS_RETRYABORT_ID = NativeUInt(10);
  BUTTONS_REPLACESKIPRENAMEABORT_ID = NativeUInt(11);
  BUTTONS_DELETECANCEL_ID = NativeUInt(12);
  BUTTONS_SKIPABORT_ID = NativeUInt(13);
  BUTTONS_YESNO_ID = NativeUInt(14);
  BUTTONS_REPLACECANCEL_ID = NativeUInt(15);
  BUTTONS_OKSKIPABORT_ID = NativeUInt(16);
  BUTTONS_YESSKIPCANCEL_ID = NativeUInt(17);
  BUTTONS_RETRYCANCEL_ID = NativeUInt(18);
  BUTTONS_YESNOCANCEL_ID = NativeUInt(19);
  BUTTONS_RENAMEREPLACESKIPABORT_ID = NativeUInt(20);
  BUTTONS_REPLACERENAMECANCEL_ID = NativeUInt(21);

  BUTTONS_OKA = PAnsiChar(BUTTONS_OK_ID);
  BUTTONS_OKCANCELA = PAnsiChar(BUTTONS_OKCANCEL_ID);
  BUTTONS_RETRYSKIPA = PAnsiChar(BUTTONS_RETRYSKIP_ID);
  BUTTONS_IGNORECANCELA = PAnsiChar(BUTTONS_IGNORECANCEL_ID);
  BUTTONS_RETRYSKIPABORTA = PAnsiChar(BUTTONS_RETRYSKIPABORT_ID);
  BUTTONS_SCHEDULERETRYSKIPABORTA = PAnsiChar(BUTTONS_SCHEDULERETRYSKIPABORT_ID);
  BUTTONS_REPLACESKIPABORTA = PAnsiChar(BUTTONS_REPLACESKIPABORT_ID);
  BUTTONS_UNPROTECTSKIPABORTA = PAnsiChar(BUTTONS_UNPROTECTSKIPABORT_ID);
  BUTTONS_DELETESKIPABORTA = PAnsiChar(BUTTONS_DELETESKIPABORT_ID);
  BUTTONS_RETRYABORTA = PAnsiChar(BUTTONS_RETRYABORT_ID);
  BUTTONS_REPLACESKIPRENAMEABORTA = PAnsiChar(BUTTONS_REPLACESKIPRENAMEABORT_ID);
  BUTTONS_DELETECANCELA = PAnsiChar(BUTTONS_DELETECANCEL_ID);
  BUTTONS_SKIPABORTA = PAnsiChar(BUTTONS_SKIPABORT_ID);
  BUTTONS_YESNOA = PAnsiChar(BUTTONS_YESNO_ID);
  BUTTONS_REPLACECANCELA = PAnsiChar(BUTTONS_REPLACECANCEL_ID);
  BUTTONS_OKSKIPABORTA = PAnsiChar(BUTTONS_OKSKIPABORT_ID);
  BUTTONS_YESSKIPCANCELA = PAnsiChar(BUTTONS_YESSKIPCANCEL_ID);
  BUTTONS_RETRYCANCELA = PAnsiChar(BUTTONS_RETRYCANCEL_ID);
  BUTTONS_YESNOCANCELA = PAnsiChar(BUTTONS_YESNOCANCEL_ID);
  BUTTONS_RENAMEREPLACESKIPABORTA = PAnsiChar(BUTTONS_RENAMEREPLACESKIPABORT_ID);
  BUTTONS_REPLACERENAMECANCELA = PAnsiChar(BUTTONS_REPLACERENAMECANCEL_ID);

  BUTTONS_OKW = PWideChar(BUTTONS_OK_ID);
  BUTTONS_OKCANCELW = PWideChar(BUTTONS_OKCANCEL_ID);
  BUTTONS_RETRYSKIPW = PWideChar(BUTTONS_RETRYSKIP_ID);
  BUTTONS_IGNORECANCELW = PWideChar(BUTTONS_IGNORECANCEL_ID);
  BUTTONS_RETRYSKIPABORTW = PWideChar(BUTTONS_RETRYSKIPABORT_ID);
  BUTTONS_SCHEDULERETRYSKIPABORTW = PWideChar(BUTTONS_SCHEDULERETRYSKIPABORT_ID);
  BUTTONS_REPLACESKIPABORTW = PWideChar(BUTTONS_REPLACESKIPABORT_ID);
  BUTTONS_UNPROTECTSKIPABORTW = PWideChar(BUTTONS_UNPROTECTSKIPABORT_ID);
  BUTTONS_DELETESKIPABORTW = PWideChar(BUTTONS_DELETESKIPABORT_ID);
  BUTTONS_RETRYABORTW = PWideChar(BUTTONS_RETRYABORT_ID);
  BUTTONS_REPLACESKIPRENAMEABORTW = PWideChar(BUTTONS_REPLACESKIPRENAMEABORT_ID);
  BUTTONS_DELETECANCELW = PWideChar(BUTTONS_DELETECANCEL_ID);
  BUTTONS_SKIPABORTW = PWideChar(BUTTONS_SKIPABORT_ID);
  BUTTONS_YESNOW = PWideChar(BUTTONS_YESNO_ID);
  BUTTONS_REPLACECANCELW = PWideChar(BUTTONS_REPLACECANCEL_ID);
  BUTTONS_OKSKIPABORTW = PWideChar(BUTTONS_OKSKIPABORT_ID);
  BUTTONS_YESSKIPCANCELW = PWideChar(BUTTONS_YESSKIPCANCEL_ID);
  BUTTONS_RETRYCANCELW = PWideChar(BUTTONS_RETRYCANCEL_ID);
  BUTTONS_YESNOCANCELW = PWideChar(BUTTONS_YESNOCANCEL_ID);
  BUTTONS_RENAMEREPLACESKIPABORTW = PWideChar(BUTTONS_RENAMEREPLACESKIPABORT_ID);
  BUTTONS_REPLACERENAMECANCELW = PWideChar(BUTTONS_REPLACERENAMECANCEL_ID);

  BUTTONS_OK = BUTTONS_OKW;
  BUTTONS_OKCANCEL = BUTTONS_OKCANCELW;
  BUTTONS_RETRYSKIP = BUTTONS_RETRYSKIPW;
  BUTTONS_IGNORECANCEL = BUTTONS_IGNORECANCELW;
  BUTTONS_RETRYSKIPABORT = BUTTONS_RETRYSKIPABORTW;
  BUTTONS_SCHEDULERETRYSKIPABORT = BUTTONS_SCHEDULERETRYSKIPABORTW;
  BUTTONS_REPLACESKIPABORT = BUTTONS_REPLACESKIPABORTW;
  BUTTONS_UNPROTECTSKIPABORT = BUTTONS_UNPROTECTSKIPABORTW;
  BUTTONS_DELETESKIPABORT = BUTTONS_DELETESKIPABORTW;
  BUTTONS_RETRYABORT = BUTTONS_RETRYABORTW;
  BUTTONS_REPLACESKIPRENAMEABORT = BUTTONS_REPLACESKIPRENAMEABORTW;
  BUTTONS_DELETECANCEL = BUTTONS_DELETECANCELW;
  BUTTONS_SKIPABORT = BUTTONS_SKIPABORTW;
  BUTTONS_YESNO = BUTTONS_YESNOW;
  BUTTONS_REPLACECANCEL = BUTTONS_REPLACECANCELW;
  BUTTONS_OKSKIPABORT = BUTTONS_OKSKIPABORTW;
  BUTTONS_YESSKIPCANCEL = BUTTONS_YESSKIPCANCELW;
  BUTTONS_RETRYCANCEL = BUTTONS_RETRYCANCELW;
  BUTTONS_YESNOCANCEL = BUTTONS_YESNOCANCELW;
  BUTTONS_RENAMEREPLACESKIPABORT = BUTTONS_RENAMEREPLACESKIPABORTW;
  BUTTONS_REPLACERENAMECANCEL = BUTTONS_REPLACERENAMECANCELW;

  SHOWREQF_NAMEFILTER = DWORD(1) shl 0;
  SHOWREQF_SELECTALL = DWORD(1) shl 1;
  SHOWREQF_PASSWORD = DWORD(1) shl 2;
  SHOWREQF_DEFAULTCANCEL = DWORD(1) shl 3;

type
  SHOWREQUESTDLGDATAA = record
    cbSize: UINT;
    hwndParent: HWND;
    pszTitle: LPCSTR;
    hIcon: HICON;
    pszMessage: LPCSTR;
    pszButtons: LPCSTR;
    pszStringBuf: LPSTR;
    cchStringBufMax: Integer;
    dwFlags: DWORD;
    pfnCheckInputString: PFNCHECKINPUTA;
    lParamCheckInput: LPARAM;
    pszBoolOption: LPCSTR;
    fBoolOption: BOOL;
  end;
  LPSHOWREQUESTDLGDATAA = ^SHOWREQUESTDLGDATAA;

  SHOWREQUESTDLGDATAW = record
    cbSize: UINT;
    hwndParent: HWND;
    pszTitle: LPCWSTR;
    hIcon: HICON;
    pszMessage: LPCWSTR;
    pszButtons: LPCWSTR;
    pszStringBuf: LPWSTR;
    cchStringBufMax: Integer;
    dwFlags: DWORD;
    pfnCheckInputString: PFNCHECKINPUTW;
    lParamCheckInput: LPARAM;
    pszBoolOption: LPCWSTR;
    fBoolOption: BOOL;
  end;
  LPSHOWREQUESTDLGDATAW = ^SHOWREQUESTDLGDATAW;

  SHOWREQUESTDLGDATA = SHOWREQUESTDLGDATAW;
  LPSHOWREQUESTDLGDATA = LPSHOWREQUESTDLGDATAW;

const
  NEWNAME_ABORT = 0;
  NEWNAME_SKIP = 1;
  NEWNAME_SIMPLE = 2;
  NEWNAME_WILD = 3;

  REPLACEDLGF_RESUME = DWORD(1) shl 0;
  REPLACEDLGF_NODESTINFO = DWORD(1) shl 1;
  REPLACEDLGF_READONLY = DWORD(1) shl 2;
  REPLACEDLGF_NOTHUMBS = DWORD(1) shl 3;
  REPLACEDLGF_NOIDENTICAL = DWORD(1) shl 4;

  REPLACERES_ABORT = 0;
  REPLACERES_REPLACE = 1;
  REPLACERES_REPLACEALL = 2;
  REPLACERES_SKIP = 3;
  REPLACERES_SKIPALL = 4;
  REPLACERES_SKIPIDENTICAL = 5;
  REPLACERES_RESUME = 6;
  REPLACERES_RESUMEALL = 7;
  REPLACERES_RENAME = 8;

  DELETERES_ABORT = 0;
  DELETERES_DELETE = 1;
  DELETERES_DELETEALL = 2;
  DELETERES_SKIP = 3;

  OPUSFILECHANGE_CREATE = 1;
  OPUSFILECHANGE_DELETE = 2;
  OPUSFILECHANGE_CHANGE = 3;
  OPUSFILECHANGE_MAKEDIR = 4;
  OPUSFILECHANGE_REMDIR = 5;
  OPUSFILECHANGE_REFRESH = 6;

  PROGRESSACTION_STATUSTEXTA = 1;
  PROGRESSACTION_STATUSTEXTW = 2;
  PROGRESSACTION_NEXTFILEA = 3;
  PROGRESSACTION_NEXTFILEW = 4;
  PROGRESSACTION_SETFILENAMEA = 5;
  PROGRESSACTION_SETFILENAMEW = 6;
  PROGRESSACTION_SETFILESIZE = 7;
  PROGRESSACTION_SETFILESIZE64 = 8;
  PROGRESSACTION_STEPBYTES = 9;
  PROGRESSACTION_SETBYTES = 10;
  PROGRESSACTION_SETBYTES64 = 11;
  PROGRESSACTION_SKIPFILE = 12;
  PROGRESSACTION_PERCENTMODE = 13;
  PROGRESSACTION_SETPERCENT = 14;
  PROGRESSACTION_NOPROGRESS = 15;

  NOPROGRESSF_BATCHCOPY = DWORD(1) shl 0;
  NOPROGRESSF_BATCHDELETE = DWORD(1) shl 1;
  NOPROGRESSF_NOABORT = DWORD(1) shl 2;

  PROGRESSACTION_STATUSTEXT = PROGRESSACTION_STATUSTEXTW;
  PROGRESSACTION_NEXTFILE = PROGRESSACTION_NEXTFILEW;
  PROGRESSACTION_SETFILENAME = PROGRESSACTION_SETFILENAMEW;

type
  OPUSREGKEY = Pointer;
  POPUSREGKEY = ^OPUSREGKEY;

const
  OPUSREGKEY_CLASSES_ROOT = Pointer(HKEY_CLASSES_ROOT);
  OPUSREGKEY_CURRENT_USER = Pointer(HKEY_CURRENT_USER);
  OPUSREGKEY_LOCAL_MACHINE = Pointer(HKEY_LOCAL_MACHINE);
  OPUSREGKEY_USERS = Pointer(HKEY_USERS);

  OPUSREG_ELEVATIONCANCELLED = 0;
  OPUSREG_ELEVATED = 1;
  OPUSREG_ELEVATIONNOTNEEDED = 2;

type
  PFNDOPUSCHOOSEFONTA = function(hWnd: HWND; lpChoose: LPDOPUSCHOOSEFONTA): BOOL; cdecl;
  PFNDOPUSCHOOSEFONTW = function(hWnd: HWND; lpChoose: LPDOPUSCHOOSEFONTW): BOOL; cdecl;
  PFNGETCONFIGPATHA = function(iPathType: Integer; pszBuf: LPSTR; cchMax: UINT): BOOL; cdecl;
  PFNGETCONFIGPATHW = function(iPathType: Integer; pszBuf: LPWSTR; cchMax: UINT): BOOL; cdecl;
  PFNLOADORSAVECONFIGA = function(iOperation: Integer; lpCfgData: LPDOPUSPLUGINCONFIGDATAA): BOOL; cdecl;
  PFNLOADORSAVECONFIGW = function(iOperation: Integer; lpCfgData: LPDOPUSPLUGINCONFIGDATAW): BOOL; cdecl;
  PFNGETTHUMBNAILPREFS = function(lpThumbData: LPDOPUSTHUMBNAILPREFSDATA): BOOL; cdecl;
  PFNXMLLOADFILEA = function(pszFile: LPCSTR): THandle; cdecl;
  PFNXMLLOADFILEW = function(pszFile: LPCWSTR): THandle; cdecl;
  PFNXMLSAVEFILEA = function(hXML: THandle; pszFile: LPCSTR): BOOL; cdecl;
  PFNXMLSAVEFILEW = function(hXML: THandle; pszFile: LPCWSTR): BOOL; cdecl;
  PFNXMLCREATEFILE = function: THandle; cdecl;
  PFNXMLFREEFILE = procedure(hXML: THandle); cdecl;
  PFNXMLADDCHILDNODEA = function(hXML: THandle; pszName: LPCSTR): THandle; cdecl;
  PFNXMLADDCHILDNODEW = function(hXML: THandle; pszName: LPCWSTR): THandle; cdecl;
  PFNXMLFINDCHILDNODEA = function(hXML: THandle; pszName: LPCSTR): THandle; cdecl;
  PFNXMLFINDCHILDNODEW = function(hXML: THandle; pszName: LPCWSTR): THandle; cdecl;
  PFNXMLENUMCHILDNODESA = function(hXML: THandle; pszName: LPCSTR; hPrev: THandle): THandle; cdecl;
  PFNXMLENUMCHILDNODESW = function(hXML: THandle; pszName: LPCWSTR; hPrev: THandle): THandle; cdecl;
  PFNXMLFIRSTCHILDNODE = function(hXML: THandle): THandle; cdecl;
  PFNXMLNEXTNODE = function(hXML: THandle): THandle; cdecl;
  PFNXMLDELETECHILD = function(hXML: THandle; hChild: THandle): BOOL; cdecl;
  PFNXMLDELETEALLCHILDNODES = function(hXML: THandle): BOOL; cdecl;
  PFNXMLGETNODENAMEA = function(hXML: THandle; pszName: LPSTR; pcchMax: PInteger): BOOL; cdecl;
  PFNXMLGETNODENAMEW = function(hXML: THandle; pszName: LPWSTR; pcchMax: PInteger): BOOL; cdecl;
  PFNXMLSETNODENAMEA = function(hXML: THandle; pszName: LPCSTR): BOOL; cdecl;
  PFNXMLSETNODENAMEW = function(hXML: THandle; pszName: LPCWSTR): BOOL; cdecl;
  PFNXMLGETNODEVALUEA = function(hXML: THandle; pszValue: LPSTR; pcchMax: PInteger): BOOL; cdecl;
  PFNXMLGETNODEVALUEW = function(hXML: THandle; pszValue: LPWSTR; pcchMax: PInteger): BOOL; cdecl;
  PFNXMLSETNODEVALUEA = function(hXML: THandle; pszValue: LPCSTR): BOOL; cdecl;
  PFNXMLSETNODEVALUEW = function(hXML: THandle; pszValue: LPCWSTR): BOOL; cdecl;
  PFNXMLGETNODEBOOLVALUE = function(hXML: THandle; pfValue: PBOOL): BOOL; cdecl;
  PFNXMLSETNODEBOOLVALUE = function(hXML: THandle; fValue: BOOL): BOOL; cdecl;
  PFNXMLGETNODEINTVALUE = function(hXML: THandle; piValue: PInteger): BOOL; cdecl;
  PFNXMLSETNODEINTVALUE = function(hXML: THandle; iValue: Integer): BOOL; cdecl;
  PFNXMLGETNODEDWORDVALUE = function(hXML: THandle; pdwValue: PDWORD): BOOL; cdecl;
  PFNXMLSETNODEDWORDVALUE = function(hXML: THandle; dwValue: DWORD): BOOL; cdecl;
  PFNXMLGETNODEDWORDLONGVALUE = function(hXML: THandle; pdwlValue: PDWORDLONG): BOOL; cdecl;
  PFNXMLSETNODEDWORDLONGVALUE = function(hXML: THandle; dwlValue: DWORDLONG): BOOL; cdecl;
  PFNXMLGETNODELOGFONTVALUEA = function(hXML: THandle; plfValue: PLogFontA): BOOL; cdecl;
  PFNXMLGETNODELOGFONTVALUEW = function(hXML: THandle; plfValue: PLogFontW): BOOL; cdecl;
  PFNXMLSETNODELOGFONTVALUEA = function(hXML: THandle; plfValue: PLogFontA): BOOL; cdecl;
  PFNXMLSETNODELOGFONTVALUEW = function(hXML: THandle; plfValue: PLogFontW): BOOL; cdecl;
  PFNXMLGETNODEBINARYVALUE = function(hXML: THandle; pValue: Pointer; pdwSize: PDWORD): BOOL; cdecl;
  PFNXMLSETNODEBINARYVALUE = function(hXML: THandle; pValue: Pointer; dwSize: DWORD): BOOL; cdecl;
  PFNXMLGETNODEATTRIBUTEA = function(hXML: THandle; pszAttrName: LPCSTR; pszAttrValue: LPSTR; pcchMax: PInteger): BOOL; cdecl;
  PFNXMLGETNODEATTRIBUTEW = function(hXML: THandle; pszAttrName: LPCWSTR; pszAttrValue: LPWSTR; pcchMax: PInteger): BOOL; cdecl;
  PFNXMLSETNODEATTRIBUTEA = function(hXML: THandle; pszAttrName: LPCSTR; pszAttrValue: LPCSTR): BOOL; cdecl;
  PFNXMLSETNODEATTRIBUTEW = function(hXML: THandle; pszAttrName: LPCWSTR; pszAttrValue: LPCWSTR): BOOL; cdecl;
  PFNXMLGETNODEBOOLATTRIBUTEA = function(hXML: THandle; pszAttrName: LPCSTR; pfAttrValue: PBOOL): BOOL; cdecl;
  PFNXMLGETNODEBOOLATTRIBUTEW = function(hXML: THandle; pszAttrName: LPCWSTR; pfAttrValue: PBOOL): BOOL; cdecl;
  PFNXMLSETNODEBOOLATTRIBUTEA = function(hXML: THandle; pszAttrName: LPCSTR; fAttrValue: BOOL): BOOL; cdecl;
  PFNXMLSETNODEBOOLATTRIBUTEW = function(hXML: THandle; pszAttrName: LPCWSTR; fAttrValue: BOOL): BOOL; cdecl;
  PFNXMLGETNODEINTATTRIBUTEA = function(hXML: THandle; pszAttrName: LPCSTR; piAttrValue: PInteger): BOOL; cdecl;
  PFNXMLGETNODEINTATTRIBUTEW = function(hXML: THandle; pszAttrName: LPCWSTR; piAttrValue: PInteger): BOOL; cdecl;
  PFNXMLSETNODEINTATTRIBUTEA = function(hXML: THandle; pszAttrName: LPCSTR; iAttrValue: Integer): BOOL; cdecl;
  PFNXMLSETNODEINTATTRIBUTEW = function(hXML: THandle; pszAttrName: LPCWSTR; iAttrValue: Integer): BOOL; cdecl;
  PFNXMLGETNODEDWORDATTRIBUTEA = function(hXML: THandle; pszAttrName: LPCSTR; pdwAttrValue: PDWORD): BOOL; cdecl;
  PFNXMLGETNODEDWORDATTRIBUTEW = function(hXML: THandle; pszAttrName: LPCWSTR; pdwAttrValue: PDWORD): BOOL; cdecl;
  PFNXMLSETNODEDWORDATTRIBUTEA = function(hXML: THandle; pszAttrName: LPCSTR; dwAttrValue: DWORD): BOOL; cdecl;
  PFNXMLSETNODEDWORDATTRIBUTEW = function(hXML: THandle; pszAttrName: LPCWSTR; dwAttrValue: DWORD): BOOL; cdecl;
  PFNXMLGETNODEDWORDLONGATTRIBUTEA = function(hXML: THandle; pszAttrName: LPCSTR; pdwlAttrValue: PDWORDLONG): BOOL; cdecl;
  PFNXMLGETNODEDWORDLONGATTRIBUTEW = function(hXML: THandle; pszAttrName: LPCWSTR; pdwlAttrValue: PDWORDLONG): BOOL; cdecl;
  PFNXMLSETNODEDWORDLONGATTRIBUTEA = function(hXML: THandle; pszAttrName: LPCSTR; dwlAttrValue: DWORDLONG): BOOL; cdecl;
  PFNXMLSETNODEDWORDLONGATTRIBUTEW = function(hXML: THandle; pszAttrName: LPCWSTR; dwlAttrValue: DWORDLONG): BOOL; cdecl;
  PFNXMLDELETENODEATTRIBUTEA = function(hXML: THandle; pszAttrName: LPCSTR): BOOL; cdecl;
  PFNXMLDELETENODEATTRIBUTEW = function(hXML: THandle; pszAttrName: LPCWSTR): BOOL; cdecl;
  PFNXMLDELETEALLNODEATTRIBUTES = function(hXML: THandle): BOOL; cdecl;
  PFNSHOWREQUESTDLGA = function(lpDlgData: LPSHOWREQUESTDLGDATAA): Integer; cdecl;
  PFNSHOWREQUESTDLGW = function(lpDlgData: LPSHOWREQUESTDLGDATAW): Integer; cdecl;
  PFNSHOWFUNCTIONNEWNAMEDLGA = function(lpFuncData: Pointer; lpszOldName: LPSTR; cchOldNameMax: Integer; lpszNewName: LPSTR; cchNewNameMax: Integer; fMove: BOOL): Integer; cdecl;
  PFNSHOWFUNCTIONNEWNAMEDLGW = function(lpFuncData: Pointer; lpszOldName: LPWSTR; cchOldNameMax: Integer; lpszNewName: LPWSTR; cchNewNameMax: Integer; fMove: BOOL): Integer; cdecl;
  PFNGETWILDNEWNAMEA = function(lpszOldPattern: LPCSTR; lpszNewPattern: LPCSTR; lpszFileName: LPCSTR; lpszNewName: LPSTR; cchNewNameMax: Integer): BOOL; cdecl;
  PFNGETWILDNEWNAMEW = function(lpszOldPattern: LPCWSTR; lpszNewPattern: LPCWSTR; lpszFileName: LPCWSTR; lpszNewName: LPWSTR; cchNewNameMax: Integer): BOOL; cdecl;
  PFNSHOWFUNCTIONERRORDLGA = function(lpFuncData: Pointer; uiType: UINT; iErrorCode: Integer; uiAction: UINT; lpszName: LPCSTR; lpszErrMsg: LPCSTR): Integer; cdecl;
  PFNSHOWFUNCTIONERRORDLGW = function(lpFuncData: Pointer; uiType: UINT; iErrorCode: Integer; uiAction: UINT; lpszName: LPCWSTR; lpszErrMsg: LPCWSTR): Integer; cdecl;
  PFNSHOWFUNCTIONREPLACEDLGA = function(lpFuncData: Pointer; pszSource: LPCSTR; pwfdSource: PWin32FindDataA; pszDest: LPCSTR; pwfdDest: PWin32FindDataA; pszNewName: LPSTR; cchNewNameMax: Integer; dwFlags: DWORD): Integer; cdecl;
  PFNSHOWFUNCTIONREPLACEDLGW = function(lpFuncData: Pointer; pszSource: LPCWSTR; pwfdSource: PWin32FindDataW; pszDest: LPCWSTR; pwfdDest: PWin32FindDataW; pszNewName: LPWSTR; cchNewNameMax: Integer; dwFlags: DWORD): Integer; cdecl;
  PFNSHOWFUNCTIONINITIALDELETEDLGA = function(lpFuncData: Pointer; pszFileName: LPCSTR): Integer; cdecl;
  PFNSHOWFUNCTIONINITIALDELETEDLGW = function(lpFuncData: Pointer; pszFileName: LPCWSTR): Integer; cdecl;
  PFNSHOWFUNCTIONDELETEDLGA = function(lpFuncData: Pointer; pszFileName: LPCSTR; fFolder: BOOL; dwFileCount: DWORD; dwFileSizeHigh: DWORD; dwFileSizeLow: DWORD): Integer; cdecl;
  PFNSHOWFUNCTIONDELETEDLGW = function(lpFuncData: Pointer; pszFileName: LPCWSTR; fFolder: BOOL; dwFileCount: DWORD; dwFileSizeHigh: DWORD; dwFileSizeLow: DWORD): Integer; cdecl;
  PFNFILTERFUNCTIONFILEA = function(lpFuncData: Pointer; lpszFile: LPCSTR; lpWFD: PWin32FindDataA; fSubFolderFilter: BOOL): BOOL; cdecl;
  PFNFILTERFUNCTIONFILEW = function(lpFuncData: Pointer; lpszFile: LPCWSTR; lpWFD: PWin32FindDataW; fSubFolderFilter: BOOL): BOOL; cdecl;
  PFNADDFUNCTIONFILECHANGEA = procedure(lpFuncData: Pointer; fIsDest: BOOL; iType: Integer; lpszFile: LPCSTR); cdecl;
  PFNADDFUNCTIONFILECHANGEW = procedure(lpFuncData: Pointer; fIsDest: BOOL; iType: Integer; lpszFile: LPCWSTR); cdecl;
  PFNUPDATEFUNCTIONPROGRESSBAR = procedure(lpFuncData: Pointer; uiAction: UINT; dwData: DWORD_PTR); cdecl;
  PFNISUSBINSTALL = function: BOOL; cdecl;
  PFNDRAWPICTUREFRAMEINDIB = function(pBMI: PBitmapInfo; pBits: Pointer; prc: PRect; iFrameSize: Integer; iShadowSize: Integer): BOOL; cdecl;
  PFNGETFUNCTIONWINDOW = function(lpFuncData: Pointer): HWND; cdecl;
  PFNCALCCRC32 = function(dwCRCIn: DWORD; pData: LPCBYTE; dwSize: DWORD): DWORD; cdecl;
  PFNGETPROGRAMDIRA = function(pszBuf: LPSTR; cchBufSize: Integer): BOOL; cdecl;
  PFNGETPROGRAMDIRW = function(pszBuf: LPWSTR; cchBufSize: Integer): BOOL; cdecl;
  // Reverse-engineered helper export from dopus.exe. This signature is not documented
  // in the official Directory Opus SDK and was recovered from local binary analysis.
  PFNLOGDIAGNOSTIC = procedure(pszSource: LPCWSTR; pszMessage: LPCWSTR; fPlain: BOOL); cdecl;
  PFNOPUSREGOPENKEYW = function(hKey: OPUSREGKEY; lpSubKey: LPCWSTR; samDesired: REGSAM; phkResult: POPUSREGKEY): Longint; cdecl;
  PFNOPUSREGCREATEKEYW = function(hKey: OPUSREGKEY; lpSubKey: LPCWSTR; samDesired: REGSAM; phkResult: POPUSREGKEY): Longint; cdecl;
  PFNOPUSREGQUERYVALUEW = function(phKey: OPUSREGKEY; lpValueName: LPCWSTR; lpType: PDWORD; lpData: LPBYTE; lpcbData: PDWORD): Longint; cdecl;
  PFNOPUSREGCLOSEKEY = function(phKey: OPUSREGKEY): Longint; cdecl;
  PFNOPUSREGDELETEKEYW = function(phKey: OPUSREGKEY; lpSubKey: LPCWSTR): Longint; cdecl;
  PFNOPUSREGDELETEVALUEW = function(phKey: OPUSREGKEY; lpValueName: LPCWSTR): Longint; cdecl;
  PFNOPUSREGSETVALUEW = function(phKey: OPUSREGKEY; lpValueName: LPCWSTR; dwType: DWORD; lpData: LPCBYTE; cbData: DWORD): Longint; cdecl;
  PFNOPUSREGCHECKELEVATION = function(phKey: OPUSREGKEY; hWnd: HWND): Longint; cdecl;
  PFNDISABLEWOW64REDIRECTION = function: THandle; cdecl;
  PFNREVERTWOW64REDIRECTION = procedure(hHandle: THandle); cdecl;

  PFNDOPUSCHOOSEFONT = PFNDOPUSCHOOSEFONTW;
  PFNGETCONFIGPATH = PFNGETCONFIGPATHW;
  PFNLOADORSAVECONFIG = PFNLOADORSAVECONFIGW;
  PFNXMLLOADFILE = PFNXMLLOADFILEW;
  PFNXMLSAVEFILE = PFNXMLSAVEFILEW;
  PFNXMLADDCHILDNODE = PFNXMLADDCHILDNODEW;
  PFNXMLFINDCHILDNODE = PFNXMLFINDCHILDNODEW;
  PFNXMLENUMCHILDNODES = PFNXMLENUMCHILDNODESW;
  PFNXMLGETNODENAME = PFNXMLGETNODENAMEW;
  PFNXMLSETNODENAME = PFNXMLSETNODENAMEW;
  PFNXMLGETNODEVALUE = PFNXMLGETNODEVALUEW;
  PFNXMLSETNODEVALUE = PFNXMLSETNODEVALUEW;
  PFNXMLGETNODELOGFONTVALUE = PFNXMLGETNODELOGFONTVALUEW;
  PFNXMLSETNODELOGFONTVALUE = PFNXMLSETNODELOGFONTVALUEW;
  PFNXMLGETNODEATTRIBUTE = PFNXMLGETNODEATTRIBUTEW;
  PFNXMLSETNODEATTRIBUTE = PFNXMLSETNODEATTRIBUTEW;
  PFNXMLGETNODEBOOLATTRIBUTE = PFNXMLGETNODEBOOLATTRIBUTEW;
  PFNXMLSETNODEBOOLATTRIBUTE = PFNXMLSETNODEBOOLATTRIBUTEW;
  PFNXMLGETNODEINTATTRIBUTE = PFNXMLGETNODEINTATTRIBUTEW;
  PFNXMLSETNODEINTATTRIBUTE = PFNXMLSETNODEINTATTRIBUTEW;
  PFNXMLGETNODEDWORDATTRIBUTE = PFNXMLGETNODEDWORDATTRIBUTEW;
  PFNXMLSETNODEDWORDATTRIBUTE = PFNXMLSETNODEDWORDATTRIBUTEW;
  PFNXMLGETNODEDWORDLONGATTRIBUTE = PFNXMLGETNODEDWORDLONGATTRIBUTEW;
  PFNXMLSETNODEDWORDLONGATTRIBUTE = PFNXMLSETNODEDWORDLONGATTRIBUTEW;
  PFNXMLDELETENODEATTRIBUTE = PFNXMLDELETENODEATTRIBUTEW;
  PFNSHOWREQUESTDLG = PFNSHOWREQUESTDLGW;
  PFNSHOWFUNCTIONNEWNAMEDLG = PFNSHOWFUNCTIONNEWNAMEDLGW;
  PFNGETWILDNEWNAME = PFNGETWILDNEWNAMEW;
  PFNSHOWFUNCTIONERRORDLG = PFNSHOWFUNCTIONERRORDLGW;
  PFNSHOWFUNCTIONREPLACEDLG = PFNSHOWFUNCTIONREPLACEDLGW;
  PFNSHOWFUNCTIONINITIALDELETEDLG = PFNSHOWFUNCTIONINITIALDELETEDLGW;
  PFNSHOWFUNCTIONDELETEDLG = PFNSHOWFUNCTIONDELETEDLGW;
  PFNFILTERFUNCTIONFILE = PFNFILTERFUNCTIONFILEW;
  PFNADDFUNCTIONFILECHANGE = PFNADDFUNCTIONFILECHANGEW;
  PFNGETPROGRAMDIR = PFNGETPROGRAMDIRW;

const
  FUNCNAME_DOPUSCHOOSEFONT = 'DOpusChooseFontW';
  FUNCNAME_GETCONFIGPATH = 'GetConfigPathW';
  FUNCNAME_LOADORSAVECONFIG = 'LoadOrSaveConfigW';
  FUNCNAME_XMLLOADFILE = 'XMLLoadFileW';
  FUNCNAME_XMLSAVEFILE = 'XMLSaveFileW';
  FUNCNAME_XMLADDCHILDNODE = 'XMLAddChildNodeW';
  FUNCNAME_XMLFINDCHILDNODE = 'XMLFindChildNodeW';
  FUNCNAME_XMLENUMCHILDNODES = 'XMLEnumChildNodesW';
  FUNCNAME_XMLGETNODENAME = 'XMLGetNodeNameW';
  FUNCNAME_XMLSETNODENAME = 'XMLSetNodeNameW';
  FUNCNAME_XMLGETNODEVALUE = 'XMLGetNodeValueW';
  FUNCNAME_XMLSETNODEVALUE = 'XMLSetNodeValueW';
  FUNCNAME_XMLGETNODELOGFONTVALUE = 'XMLGetNodeLOGFONTValueW';
  FUNCNAME_XMLSETNODELOGFONTVALUE = 'XMLSetNodeLOGFONTValueW';
  FUNCNAME_XMLGETNODEATTRIBUTE = 'XMLGetNodeAttributeW';
  FUNCNAME_XMLSETNODEATTRIBUTE = 'XMLSetNodeAttributeW';
  FUNCNAME_XMLGETNODEBOOLATTRIBUTE = 'XMLGetNodeBoolAttributeW';
  FUNCNAME_XMLSETNODEBOOLATTRIBUTE = 'XMLSetNodeBoolAttributeW';
  FUNCNAME_XMLGETNODEINTATTRIBUTE = 'XMLGetNodeIntAttributeW';
  FUNCNAME_XMLSETNODEINTATTRIBUTE = 'XMLSetNodeIntAttributeW';
  FUNCNAME_XMLGETNODEDWORDATTRIBUTE = 'XMLGetNodeDWORDAttributeW';
  FUNCNAME_XMLSETNODEDWORDATTRIBUTE = 'XMLSetNodeDWORDAttributeW';
  FUNCNAME_XMLGETNODEDWORDLONGATTRIBUTE = 'XMLGetNodeDWORDLONGAttributeW';
  FUNCNAME_XMLSETNODEDWORDLONGATTRIBUTE = 'XMLSetNodeDWORDLONGAttributeW';
  FUNCNAME_XMLDELETENODEATTRIBUTE = 'XMLDeleteNodeAttributeW';
  FUNCNAME_SHOWREQUESTDLG = 'ShowRequestDlgW';
  FUNCNAME_SHOWFUNCTIONNEWNAMEDLG = 'ShowFunctionNewNameDlgW';
  FUNCNAME_GETWILDNEWNAME = 'GetWildNewNameW';
  FUNCNAME_SHOWFUNCTIONERRORDLG = 'ShowFunctionErrorDlgW';
  FUNCNAME_SHOWFUNCTIONREPLACEDLG = 'ShowFunctionReplaceDlgW';
  FUNCNAME_SHOWFUNCTIONINITIALDELETEDLG = 'ShowFunctionInitialDeleteDlgW';
  FUNCNAME_SHOWFUNCTIONDELETEDLG = 'ShowFunctionDeleteDlgW';
  FUNCNAME_FILTERFUNCTIONFILE = 'FilterFunctionFileW';
  FUNCNAME_ADDFUNCTIONFILECHANGE = 'AddFunctionFileChangeW';
  FUNCNAME_GETPROGRAMDIR = 'GetProgramDirW';
  // Reverse-engineered helper export from dopus.exe. Not part of the official SDK docs.
  FUNCNAME_LOGDIAGNOSTIC = 'LogDiagnostic';
  FUNCNAME_GETTHUMBNAILPREFS = 'GetThumbnailPrefs';
  FUNCNAME_XMLCREATEFILE = 'XMLCreateFile';
  FUNCNAME_XMLFREEFILE = 'XMLFreeFile';
  FUNCNAME_XMLFIRSTCHILDNODE = 'XMLFirstChildNode';
  FUNCNAME_XMLNEXTNODE = 'XMLNextNode';
  FUNCNAME_XMLGETNODEBOOLVALUE = 'XMLGetNodeBoolValue';
  FUNCNAME_XMLSETNODEBOOLVALUE = 'XMLSetNodeBoolValue';
  FUNCNAME_XMLGETNODEINTVALUE = 'XMLGetNodeIntValue';
  FUNCNAME_XMLSETNODEINTVALUE = 'XMLSetNodeIntValue';
  FUNCNAME_XMLGETNODEDWORDVALUE = 'XMLGetNodeDWORDValue';
  FUNCNAME_XMLSETNODEDWORDVALUE = 'XMLSetNodeDWORDValue';
  FUNCNAME_XMLGETNODEDWORDLONGVALUE = 'XMLGetNodeDWORDLONGValue';
  FUNCNAME_XMLSETNODEDWORDLONGVALUE = 'XMLSetNodeDWORDLONGValue';
  FUNCNAME_XMLGETNODEBINARYVALUE = 'XMLGetNodeBinaryValue';
  FUNCNAME_XMLSETNODEBINARYVALUE = 'XMLSetNodeBinaryValue';
  FUNCNAME_XMLDELETECHILD = 'XMLDeleteChild';
  FUNCNAME_XMLDELETEALLCHILDNODES = 'XMLDeleteAllChildNodes';
  FUNCNAME_XMLDELETEALLNODEATTRIBUTES = 'XMLDeleteAllNodeAttributes';
  FUNCNAME_UPDATEFUNCTIONPROGRESSBAR = 'UpdateFunctionProgressBar';
  FUNCNAME_ISUSBINSTALL = 'IsUSBInstall';
  FUNCNAME_DRAWPICTUREFRAMEINDIB = 'DrawPictureFrameInDIB';
  FUNCNAME_GETFUNCTIONWINDOW = 'GetFunctionWindow';
  FUNCNAME_CALCCRC32 = 'CalcCRC32';
  FUNCNAME_OPUSREGOPENKEYW = 'OpusRegOpenKeyW';
  FUNCNAME_OPUSREGCREATEKEYW = 'OpusRegCreateKeyW';
  FUNCNAME_OPUSREGQUERYVALUEW = 'OpusRegQueryValueW';
  FUNCNAME_OPUSREGCLOSEKEY = 'OpusRegCloseKey';
  FUNCNAME_OPUSREGDELETEKEYW = 'OpusRegDeleteKeyW';
  FUNCNAME_OPUSREGDELETEVALUEW = 'OpusRegDeleteValueW';
  FUNCNAME_OPUSREGSETVALUEW = 'OpusRegSetValueW';
  FUNCNAME_OPUSREGCHECKELEVATION = 'OpusRegCheckElevation';
  FUNCNAME_DISABLEWOW64REDIRECTION = 'DisableWow64Redirection';
  FUNCNAME_REVERTWOW64REDIRECTION = 'RevertWow64Redirection';

implementation

end.


